icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
separator = "/"
separator_bg = "{background}"
separator_fg = "{foreground}"
idle_bg = "{background}"
idle_fg = "{foreground}"
info_bg = "{background}"
info_fg = "{foreground}"

[[block]]
block = "sound"

[[block]]
block = "music"
buttons = ["play", "next"]
marquee = false
max_width = 25

[[block]]
block = "time"
interval = 60
format = "%Y-%d-%m %l:%M"

