#!/usr/bin/perl
# Copyright (C) 2014 Tony Crisci <tony@dubstepdish.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Requires playerctl binary to be in your path (except cmus)
# See: https://github.com/acrisci/playerctl

# Set instance=NAME in the i3blocks configuration to specify a music player
# (playerctl will attempt to connect to org.mpris.MediaPlayer2.[NAME] on your
# DBus session).

use Env qw(BLOCK_INSTANCE);

my @metadata = ();

if ($ENV{'BLOCK_BUTTON'} == 1) {
    system("playerctl previous");
} elsif ($ENV{'BLOCK_BUTTON'} == 2) {
    system("playerctl play-pause");
} elsif ($ENV{'BLOCK_BUTTON'} == 3) {
    system("playerctl next");
}

my $artist = qx(playerctl metadata artist 2> /dev/null);
chomp $artist;
# exit status will be nonzero when playerctl cannot find your player
exit(0) if $?;
push(@metadata, $artist) if $artist;

my $title = qx(playerctl metadata title 2> /dev/null);
exit(0) if $?;
push(@metadata, $title) if $title;

print(join(" - ", @metadata)) if @metadata;
